version: "3.8"

services:
  dev:
    build:
      context: .
      args:
        RUN_ENV: DEV
    container_name: nvim-python
    restart: always
    volumes:
      - .:/app:z
      - ./myvim/local/share/nvim:/home/dev/.local/share/nvim:z
      - ~/.config/nvim:/home/dev/.config/nvim:z
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY:z
    stdin_open: true
    tty: true
    user: 1000:1000
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR: /home/dev/.config/zsh
        #    security_opt:  #This this if copying to system clipboard fails.  Needed with moby engine but not Docker proper.
        #      - label:type:container_runtime_t
