version: "3.8"

services:
  dev:
    build:
      context: .
      args:
        #Replace with results of $(id -u) and $(id -g) if necessary
        UID: 1000
        GRP: 1000
    container_name: neovim
    restart: always
    volumes:
      - ./app:/app:z
      - dotlocal:/home/app/.local
      - ~/.config/nvim:/home/app/.config/nvim:z
      - ~/.config/tmux:/home/app/.config/tmux:z
      - ~/.ssh:/home/app/.ssh:z
      - ~/.gitconfig:/home/app/.gitconfig:z
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY:z
    stdin_open: true
    tty: true
    user: 1000:1000 #Replace with results of $(id -u) and $(id -g) if necessary
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR: /home/app/.config/zsh
        #    security_opt:  #This this if copying to system clipboard fails.  Needed with moby engine but not Docker proper.
        #      - label:type:container_runtime_t
volumes:
  dotlocal:
