version: "3.8"

services:
  dev:
    build:
      context: .
      args:
        RUN_ENV: DEV
    container_name: neovim-python
    restart: always
    volumes:
      - .:/app:z
      - /home/dev/.local/share/nvim:/home/dev/.local/share/nvim:z
      - /home/dev/.config:/home/dev/.config/:z
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY:z
    stdin_open: true
    tty: true
    user: 1000:1000
    environment:
      XDG_RUNTIME_DIR: /tmp
      TERM: xterm-256color
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_DATA_DIRS: /tmp/XDG_DATA_DIRS
      ZDOTDIR: /home/dev/.config/zsh
    security_opt:
      - label:type:container_runtime_t
    ports:
      - 3000:3000
